// JWT token management for admin authentication
// Tokens are generated by admin.psilyou.com and passed via ?token= URL parameter
// See: JWT structure documentation version 1.0 (2025-11-07)

const TOKEN_KEY = "admin_jwt_token";
const ADMIN_LOGIN_URL = "https://admin.psilyou.com";

export interface DecodedToken {
  id: number;
  user_email: string;
  first_name: string;
  last_name: string;
  sub_type: number;
  iat: number;
  exp: number;
}

// Extract token from URL query parameter (?token=)
export function extractTokenFromUrl(): string | null {
  if (typeof window === "undefined") return null;
  
  const urlParams = new URLSearchParams(window.location.search);
  const token = urlParams.get("token");
  
  if (token) {
    // Store token in localStorage
    setAuthToken(token);
    
    // Clean up URL (remove token parameter for security)
    const url = new URL(window.location.href);
    url.searchParams.delete("token");
    window.history.replaceState({}, "", url.toString());
    
    return token;
  }
  
  return null;
}

// Decode JWT payload (client-side only - doesn't verify signature)
export function decodeToken(token: string): DecodedToken | null {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return null;
    
    // Convert base64url to standard base64
    // JWT uses base64url encoding: replace '-' with '+' and '_' with '/'
    // Then add padding if needed
    let base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    
    // Add padding if needed
    const pad = base64.length % 4;
    if (pad) {
      if (pad === 1) {
        throw new Error('Invalid base64url string');
      }
      base64 += new Array(5 - pad).join('=');
    }
    
    const payload = JSON.parse(atob(base64));
    return payload as DecodedToken;
  } catch {
    return null;
  }
}

// Check if token is expired
export function isTokenExpired(token: string): boolean {
  const decoded = decodeToken(token);
  if (!decoded) return true;
  
  const now = Math.floor(Date.now() / 1000);
  return decoded.exp < now;
}

// Get current user info from token
export function getCurrentUser(): DecodedToken | null {
  const token = getAuthToken();
  if (!token) return null;
  
  return decodeToken(token);
}

export function getAuthToken(): string | null {
  if (typeof window === "undefined") return null;
  return localStorage.getItem(TOKEN_KEY);
}

export function setAuthToken(token: string): void {
  if (typeof window === "undefined") return;
  localStorage.setItem(TOKEN_KEY, token);
}

export function clearAuthToken(): void {
  if (typeof window === "undefined") return;
  localStorage.removeItem(TOKEN_KEY);
}

export function isAuthenticated(): boolean {
  const token = getAuthToken();
  if (!token) return false;
  
  // Check if token is expired
  if (isTokenExpired(token)) {
    clearAuthToken();
    return false;
  }
  
  return true;
}

// Redirect to admin login page
export function redirectToLogin(): void {
  if (typeof window === "undefined") return;
  window.location.href = ADMIN_LOGIN_URL;
}

// For development only: generate a mock JWT
export function getMockToken(): string {
  // Only use in development mode
  if (import.meta.env.DEV) {
    return "dev-mock-token";
  }
  return "";
}
